### ISSUE TITLE
Feature Request: Telegram sticker, picture and GIF support

### ISSUE THREAD

**Issue by TomTheDragon** [42wim/matterbridge#184]
### Which version of matterbridge are you using?
0.12.1

### Desciption of the request
Is there a way to make Telegram stickers or GIFs (which are actually mp4 files) visible to other bridged chats? As a link perhaps?

**Comment by 42wim** [comment]
I've added this to master, but I don't have telegram myself, so I can't test it.
Could you rebuild from master and let me know if it works ?:)

**Comment by TomTheDragon** [comment]
Okay so i rebuild Matterbridge and tested even some other media types:

GIFs show up just fine:
<bot> [Tom]  animation.gif.mp4 : https://api.telegram.org/file/bot000000000:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/animations/animation.gif.mp4

Same with Stickers ..the webp format is still a bit strange but i guess there is not much you can do about:
<bot> [Tom]  https://api.telegram.org/file/bot000000000:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/stickers/000000000000000000.webp

Normal pictures work fine too but it sends out tree different versions to the chat but really one the biggest view is needed (the last link):
<bot> [Tom]  https://api.telegram.org/file/bot000000000:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/photos/0000000000000000000.jpg https://api.telegram.org/file/bot000000000:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/photos/file_0.jpg https://api.telegram.org/file/bot000000000:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/photos/file_1.jpg

Sound and also file transfers dont seem to work for now but thats fine i think :)

**Comment by 42wim** [comment]
Thanks for testing and reporting.

Is the webp viewable in something? otherwise it's not useful to send those stickers :-)
About the images, is it always the last image that's correct ? The other ones are just different sizes ?

**Comment by TomTheDragon** [comment]
Some browsers do support it directly and Irfanview also seems to support it.. but i think there must be also a png version stored on the server, since the browser-version of Telegram also works on Firefox (which does not support webp)

Yes, the first one is just a very simple preview, which you see if you have auto download of pictures turned off, the second one if the small version of the picture, which is displayed in the window and the last one is the picture in full size (what you see if you click on the picture).

**Comment by 42wim** [comment]
Ok, I've changed it so that only the last image is sent.
About the sticker thing, the API seems to work with fileids, so maybe sometimes stickers get upload as webp, sometimes as png.

If I broke it, reopen the ticket ;-)

**Comment by TomTheDragon** [comment]
Ah thanks, well i just noticed that Discord can display webp in the chat, so when someone sends out an sticker in Telegram, it gets displayed perfectly (minus the link) in Discord ;)

**Comment by TomTheDragon** [comment]
Meh.. after some "proper" testing, i now can confirm that pictures dont seem to work any more :/

**Comment by 42wim** [comment]
You don't get to see a link?

**Comment by TomTheDragon** [comment]
No there is simply nothing, not even a empty post.

**Comment by 42wim** [comment]
Do you have now some time to spare to debug this ? 
If yes, could you join the chat? (eg #matterbridgechat on freenode or https://discord.gg/AkKPtrQ on discord)

If no, we'll try doing it via this issue :)

**Comment by 42wim** [comment]
Ok, should be fixed now :-)
You can run a ```go get -u github.com/42wim/matterbridge``` to rebuild

**Comment by TomTheDragon** [comment]
I recently upgraded to the newest build and now, everything stopped working.. so not stickers, pictures or GIFs

**Comment by TomTheDragon** [comment]
Meh.. sorry but i dont check the changelog every time i update :P
But thanks for the quick help, its working now :)

**Comment by TomTheDragon** [comment]
This is not longer working for some time now.
I am sorry that i am kind of late for this but i am mainly on Telegram, so i did not notice that the bridge is no longer sending media links to the other networks.
I also tried to go back to older builds from like 4 months ago but this did not fix the problem. I also noticed that all the older media links seem to be dead now, so maybe the changed something on the server side.

**Comment by 42wim** [comment]
what other networks are you using ? because if they have native upload support (discord, mattermost, slack, matrix) it's better to use that instead of insecure url.

Another reason is that maybe they blocked the bot, try creating a new bot ?

**Comment by TomTheDragon** [comment]
I also use IRC, Discord and XMPP and it also seems to work fine in all directions.. the only thing that dont seem to work sine some while ago, is receiving media on all the other networks, when it comes from the Telegram side.
Yes i also wanted to give this a try, because it sure will be the better solution over the long run, but i had some problems setting up this one webserver for the uploads, thats recommended in the wiki.
Cant i use something else like nginx?

And no i dont think its blocked, since everything else gets through.

**Comment by 42wim** [comment]
I don't know if you can use nginx, I don't know all of its features.
I picked caddy because single-binary and easy to setup.

But the UseInsecureURL thing should still work. 

* Could you paste your full config (be sure to remove tokens)
* Try running the latest version (I've just added extra debug info) in `-debug`  and then sending media from telegram.
Watch for `Setting message text to ... module=telegram` and `Message is .... module=telegram`

Does the `setting message text to` contains the correct url ?

The lastest binaries can be found here https://bintray.com/42wim/nightly/Matterbridge/v1.7.1-30-ga2b9445#files

**Comment by TomTheDragon** [comment]
Thats my config: (i used a simpler one for testing but the problem is still there)
======================
[discord]
[discord.BLA]
Token="[Token]"
Server="000000000000000000"
EditSuffix=""
ShowJoinPart=true
ShowEmbeds=true
RemoteNickFormat="**[{NICK}]** "
#RemoteNickFormat="{NICK}: "
EditDisable=false
ReplaceNicks=[ ["Tatsumaki","INFO"] ]
IgnoreNicks="Rythm"
ShowTopicChange=false

[telegram]
[telegram.TG_BOT]
Token="[Token]"
MessageFormat="HTML"
UseFirstName=true
EditSuffix=""
ShowJoinPart=true
UseInsecureURL=true
RemoteNickFormat="[{NICK}] "
#RemoteNickFormat="{NICK}: "
EditDisable=false
ReplaceNicks=[ ["Welcome Bot","INFO"] ]

[general]

[[gateway]]
name="TEST_STUFF"
enable=true
    [[gateway.inout]]
        account="telegram.TG_BOT"
        channel="-222222222"
    [[gateway.inout]]
        account="discord.BLA"
        channel="ID:111111111111111111"
======================

I did post a text on Discord and then send an picture, i then did the same on Telegram.

Thats my log:
======================
time="2018-02-20T20:55:41+01:00" level=info msg="Gateway(s) started succesfully. Now relaying messages" 
time="2018-02-20T20:56:09+01:00" level=debug msg="Receiving message &discordgo.Message{ID:"415597515304599555", ChannelID:"111111111111111111", Content:"test on discord", Timestamp:"2018-02-20T19:56:09.077000+00:00", EditedTimestamp:"", MentionRoles:[]string{}, Tts:false, MentionEveryone:false, Author:(*discordgo.User)(0xc420134af0), Attachments:[]*discordgo.MessageAttachment{}, Embeds:[]*discordgo.MessageEmbed{}, Mentions:[]*discordgo.User{}, Reactions:[]*discordgo.MessageReactions(nil), Type:0}" module=discord 
time="2018-02-20T20:56:09+01:00" level=debug msg="Sending message from TomTheDragon on discord.BLA to gateway" module=discord 
time="2018-02-20T20:56:09+01:00" level=debug msg="Message is config.Message{Text:"test on discord", Channel:"ID:111111111111111111", Username:"TomTheDragon", UserID:"77777777777777777", Avatar:"https://cdn.discordapp.com/avatars/92777019607121920/3d0ffeeed8c4edc173f7c76c778098a2.jpg", Account:"discord.BLA", Event:"", Protocol:"", Gateway:"", Timestamp:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, ID:"415597515304599555", Extra:map[string][]interface {}(nil)}" module=discord 
time="2018-02-20T20:56:09+01:00" level=debug msg="Sending config.Message{Text:"test on discord", Channel:"ID:111111111111111111", Username:"TomTheDragon", UserID:"77777777777777777", Avatar:"https://cdn.discordapp.com/avatars/92777019607121920/3d0ffeeed8c4edc173f7c76c778098a2.jpg", Account:"discord.BLA", Event:"", Protocol:"", Gateway:"TEST_STUFF", Timestamp:time.Time{wall:0xbe9b3d364f07ab6b, ext:29612261556, loc:(*time.Location)(0x14bd780)}, ID:"415597515304599555", Extra:map[string][]interface {}(nil)} from discord.BLA (ID:111111111111111111) to telegram.TG_BOT (-222222222)" 
time="2018-02-20T20:56:09+01:00" level=debug msg="Receiving config.Message{Text:"test on discord", Channel:"-222222222", Username:"[TomTheDragon] ", UserID:"92777019607121920", Avatar:"https://cdn.discordapp.com/avatars/92777019607121920/3d0ffeeed8c4edc173f7c76c778098a2.jpg", Account:"discord.BLA", Event:"", Protocol:"", Gateway:"TEST_STUFF", Timestamp:time.Time{wall:0xbe9b3d364f07ab6b, ext:29612261556, loc:(*time.Location)(0x14bd780)}, ID:"", Extra:map[string][]interface {}(nil)}" module=telegram 
time="2018-02-20T20:56:09+01:00" level=debug msg="Using mode HTML" module=telegram 
time="2018-02-20T20:56:13+01:00" level=debug msg="Receiving message &discordgo.Message{ID:"415597531804729354", ChannelID:"111111111111111111", Content:"\nhttps://cdn.discordapp.com/attachments/111111111111111111/415597531322515467/index.jpg", Timestamp:"2018-02-20T19:56:13.011000+00:00", EditedTimestamp:"", MentionRoles:[]string{}, Tts:false, MentionEveryone:false, Author:(*discordgo.User)(0xc420165030), Attachments:[]*discordgo.MessageAttachment{(*discordgo.MessageAttachment)(0xc4208ec060)}, Embeds:[]*discordgo.MessageEmbed{}, Mentions:[]*discordgo.User{}, Reactions:[]*discordgo.MessageReactions(nil), Type:0}" module=discord 
time="2018-02-20T20:56:13+01:00" level=debug msg="Sending message from TomTheDragon on discord.BLA to gateway" module=discord 
time="2018-02-20T20:56:13+01:00" level=debug msg="Message is config.Message{Text:"\nhttps://cdn.discordapp.com/attachments/111111111111111111/415597531322515467/index.jpg", Channel:"ID:111111111111111111", Username:"TomTheDragon", UserID:"92777019607121920", Avatar:"https://cdn.discordapp.com/avatars/92777019607121920/3d0ffeeed8c4edc173f7c76c778098a2.jpg", Account:"discord.BLA", Event:"", Protocol:"", Gateway:"", Timestamp:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, ID:"415597531804729354", Extra:map[string][]interface {}(nil)}" module=discord 
time="2018-02-20T20:56:13+01:00" level=debug msg="Sending config.Message{Text:"\nhttps://cdn.discordapp.com/attachments/111111111111111111/415597531322515467/index.jpg", Channel:"ID:111111111111111111", Username:"TomTheDragon", UserID:"77777777777777777", Avatar:"https://cdn.discordapp.com/avatars/92777019607121920/3d0ffeeed8c4edc173f7c76c778098a2.jpg", Account:"discord.BLA", Event:"", Protocol:"", Gateway:"TEST_STUFF", Timestamp:time.Time{wall:0xbe9b3d374ca3542b, ext:33572131196, loc:(*time.Location)(0x14bd780)}, ID:"415597531804729354", Extra:map[string][]interface {}(nil)} from discord.BLA (ID:111111111111111111) to telegram.TG_BOT (-222222222)" 
time="2018-02-20T20:56:13+01:00" level=debug msg="Receiving config.Message{Text:"\nhttps://cdn.discordapp.com/attachments/111111111111111111/415597531322515467/index.jpg", Channel:"-222222222", Username:"[TomTheDragon] ", UserID:"77777777777777777", Avatar:"https://cdn.discordapp.com/avatars/92777019607121920/3d0ffeeed8c4edc173f7c76c778098a2.jpg", Account:"discord.BLA", Event:"", Protocol:"", Gateway:"TEST_STUFF", Timestamp:time.Time{wall:0xbe9b3d374ca3542b, ext:33572131196, loc:(*time.Location)(0x14bd780)}, ID:"", Extra:map[string][]interface {}(nil)}" module=telegram 
time="2018-02-20T20:56:13+01:00" level=debug msg="Using mode HTML" module=telegram 
time="2018-02-20T20:56:27+01:00" level=debug msg="Receiving from telegram: &tgbotapi.Message{MessageID:504, From:(*tgbotapi.User)(0xc4207d8d20), Date:1519156587, Chat:(*tgbotapi.Chat)(0xc4202707e0), ForwardFrom:(*tgbotapi.User)(nil), ForwardFromChat:(*tgbotapi.Chat)(nil), ForwardFromMessageID:0, ForwardDate:0, ReplyToMessage:(*tgbotapi.Message)(nil), EditDate:0, Text:"test on telegram", Entities:(*[]tgbotapi.MessageEntity)(nil), Audio:(*tgbotapi.Audio)(nil), Document:(*tgbotapi.Document)(nil), Game:(*tgbotapi.Game)(nil), Photo:(*[]tgbotapi.PhotoSize)(nil), Sticker:(*tgbotapi.Sticker)(nil), Video:(*tgbotapi.Video)(nil), VideoNote:(*tgbotapi.VideoNote)(nil), Voice:(*tgbotapi.Voice)(nil), Caption:"", Contact:(*tgbotapi.Contact)(nil), Location:(*tgbotapi.Location)(nil), Venue:(*tgbotapi.Venue)(nil), NewChatMembers:(*[]tgbotapi.User)(nil), LeftChatMember:(*tgbotapi.User)(nil), NewChatTitle:"", NewChatPhoto:(*[]tgbotapi.PhotoSize)(nil), DeleteChatPhoto:false, GroupChatCreated:false, SuperGroupChatCreated:false, ChannelChatCreated:false, MigrateToChatID:0, MigrateFromChatID:0, PinnedMessage:(*tgbotapi.Message)(nil), Invoice:(*tgbotapi.Invoice)(nil), SuccessfulPayment:(*tgbotapi.SuccessfulPayment)(nil)}" module=telegram 
time="2018-02-20T20:56:27+01:00" level=debug msg="Sending message from Tom on telegram.TG_BOT to gateway" module=telegram 
time="2018-02-20T20:56:27+01:00" level=debug msg="Message is config.Message{Text:"test on telegram", Channel:"-222222222", Username:"Tom", UserID:"88888888", Avatar:"", Account:"telegram.TG_BOT", Event:"", Protocol:"", Gateway:"", Timestamp:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, ID:"504", Extra:map[string][]interface {}{}}" module=telegram 
time="2018-02-20T20:56:27+01:00" level=debug msg="Sending config.Message{Text:"test on telegram", Channel:"-222222222", Username:"Tom", UserID:"88888888", Avatar:"", Account:"telegram.TG_BOT", Event:"", Protocol:"", Gateway:"TEST_STUFF", Timestamp:time.Time{wall:0xbe9b3d3ae2313700, ext:47933751365, loc:(*time.Location)(0x14bd780)}, ID:"504", Extra:map[string][]interface {}{}} from telegram.TG_BOT (-222222222) to discord.BLA (ID:111111111111111111)" 
time="2018-02-20T20:56:27+01:00" level=debug msg="Receiving config.Message{Text:"test on telegram", Channel:"ID:111111111111111111", Username:"**[Tom]** ", UserID:"88888888", Avatar:"", Account:"telegram.TG_BOT", Event:"", Protocol:"", Gateway:"TEST_STUFF", Timestamp:time.Time{wall:0xbe9b3d3ae2313700, ext:47933751365, loc:(*time.Location)(0x14bd780)}, ID:"", Extra:map[string][]interface {}{}}" module=discord 
time="2018-02-20T20:56:27+01:00" level=debug msg="Broadcasting using token (API)" module=discord 
time="2018-02-20T20:57:35+01:00" level=debug msg="Receiving from telegram: &tgbotapi.Message{MessageID:505, From:(*tgbotapi.User)(0xc4203fe140), Date:1519156655, Chat:(*tgbotapi.Chat)(0xc4202705a0), ForwardFrom:(*tgbotapi.User)(nil), ForwardFromChat:(*tgbotapi.Chat)(nil), ForwardFromMessageID:0, ForwardDate:0, ReplyToMessage:(*tgbotapi.Message)(nil), EditDate:0, Text:"", Entities:(*[]tgbotapi.MessageEntity)(nil), Audio:(*tgbotapi.Audio)(nil), Document:(*tgbotapi.Document)(nil), Game:(*tgbotapi.Game)(nil), Photo:(*[]tgbotapi.PhotoSize)(nil), Sticker:(*tgbotapi.Sticker)(0xc42022dd40), Video:(*tgbotapi.Video)(nil), VideoNote:(*tgbotapi.VideoNote)(nil), Voice:(*tgbotapi.Voice)(nil), Caption:"", Contact:(*tgbotapi.Contact)(nil), Location:(*tgbotapi.Location)(nil), Venue:(*tgbotapi.Venue)(nil), NewChatMembers:(*[]tgbotapi.User)(nil), LeftChatMember:(*tgbotapi.User)(nil), NewChatTitle:"", NewChatPhoto:(*[]tgbotapi.PhotoSize)(nil), DeleteChatPhoto:false, GroupChatCreated:false, SuperGroupChatCreated:false, ChannelChatCreated:false, MigrateToChatID:0, MigrateFromChatID:0, PinnedMessage:(*tgbotapi.Message)(nil), Invoice:(*tgbotapi.Invoice)(nil), SuccessfulPayment:(*tgbotapi.SuccessfulPayment)(nil)}" module=telegram 
======================

**Comment by 42wim** [comment]
what exactly did you send on telegram ? you attached a picture ?
The last message on telegram shows that's a sticker, is that correct ?

There was no message `Setting message text to ... module=telegram` ? and you were running the latest binaries ?

**Comment by TomTheDragon** [comment]
Yes i was trying to send a sticker but i also already tested pictures and GIFs.
I used the one you gave me and before that, i build everything myself.

**Comment by 42wim** [comment]
That's strange, maybe I gave you the wrong file.
Please try again with this version: https://bintray.com/42wim/nightly/Matterbridge/v1.7.1-39-g723a90c#files (or build yourself from master)

Please once more try running with `-debug` and sending a picture from telegram (only the telegram test is needed, you don't need to test from discord)

It should show the `Setting message text to ...` message (hopefully)

**Comment by TomTheDragon** [comment]
I did build it myself this time and still no sticker on the Discord side

Thats my log:
__________
[0048] DEBUG telegram:     Receiving from telegram: &tgbotapi.Message{MessageID:506, From:(*tgbotapi.User)(0xc4205c6dc0), Date:1519197806, Chat:(*tgbotapi.Chat)(0xc420a5c5a0), ForwardFrom:(*tgbotapi.User)(nil), ForwardFromChat:(*tgbotapi.Chat)(nil), ForwardFromMessageID:0, ForwardDate:0, ReplyToMessage:(*tgbotapi.Message)(nil), EditDate:0, Text:"", Entities:(*[]tgbotapi.MessageEntity)(nil), Audio:(*tgbotapi.Audio)(nil), Document:(*tgbotapi.Document)(nil), Game:(*tgbotapi.Game)(nil), Photo:(*[]tgbotapi.PhotoSize)(nil), Sticker:(*tgbotapi.Sticker)(0xc4205bc5c0), Video:(*tgbotapi.Video)(nil), VideoNote:(*tgbotapi.VideoNote)(nil), Voice:(*tgbotapi.Voice)(nil), Caption:"", Contact:(*tgbotapi.Contact)(nil), Location:(*tgbotapi.Location)(nil), Venue:(*tgbotapi.Venue)(nil), NewChatMembers:(*[]tgbotapi.User)(nil), LeftChatMember:(*tgbotapi.User)(nil), NewChatTitle:"", NewChatPhoto:(*[]tgbotapi.PhotoSize)(nil), DeleteChatPhoto:false, GroupChatCreated:false, SuperGroupChatCreated:false, ChannelChatCreated:false, MigrateToChatID:0, MigrateFromChatID:0, PinnedMessage:(*tgbotapi.Message)(nil), Invoice:(*tgbotapi.Invoice)(nil), SuccessfulPayment:(*tgbotapi.SuccessfulPayment)(nil)}
[0048] DEBUG telegram:     Setting message text to : https://api.telegram.org/file/bot371731426:AAH23lYAf0t3GzHcLVifFy8IV02b-pd7IgM/stickers/file_552.webp
__________

**Comment by 42wim** [comment]
@TomTheDragon should be fixed now :)

**Comment by TomTheDragon** [comment]
Yay, it seems to work again
Thx for the quick fix :)
