### ISSUE TITLE
IRC bridge shows parts, but but does not show joins

### ISSUE THREAD

**Issue by Ossssip** [42wim/matterbridge#708]
**Describe the bug**
In an irc<->matrix bridge, matterbridge delivers to the matrix side only `part` events from IRC, but no `joins`

**Screenshots/debug logs**
```
[0000]  INFO main:         Enabling debug
[0000]  INFO main:         Running version 1.13.2-dev
[0000]  INFO main:         WARNING: THIS IS A DEVELOPMENT VERSION. Things may break.
[0000]  INFO gateway:      Parsing gateway irc-to-matrix
[0000]  INFO gateway:      Starting bridge: matrix.for_irc
[0000]  INFO matrix:       Connecting https://matrix.matrixserver
[0001]  INFO matrix:       Connection succeeded
[0001]  INFO bridge:       matrix.for_irc: joining #ircchannel@ircserver:matrixserver (ID: #ircchannel@ircserver:matrixservermatrix.for_irc)
[0001]  INFO gateway:      Starting bridge: irc.ircserver
[0001]  INFO irc:          Connecting ircserver:6697
[0001] DEBUG irc:          "CLIENT_INIT :ircserver:6697"
[0001] DEBUG irc:          ":ircserver NOTICE * :*** Looking up your hostname..."
[0001] DEBUG irc:          ":ircserver NOTICE * :*** Found your hostname"
[0001] DEBUG irc:          ":ircserver CAP * LS :userhost-in-names multi-prefix away-notify account-notify tls"
[0001] DEBUG irc:          "PING :537BDCBD"
[0001] DEBUG irc:          ":ircserver CAP relay ACK :userhost-in-names multi-prefix away-notify account-notify "
[0001] DEBUG irc:          ":ircserver 001 relay :Welcome to the wonderland IRC Network relay!relay@matterbridgehost"
[0001] DEBUG irc:          Registering callbacks
[0001] DEBUG irc:          ":ircserver 002 relay :Your host is ircserver, running version UnrealIRCd-4.0.10"
[0001] DEBUG irc:          ":ircserver 003 relay :This server was created Wed Feb 1 2017 at 15:31:00 CET"
[0001] DEBUG irc:          ":ircserver 004 relay ircserver UnrealIRCd-4.0.10 iowrsxzdHtIDRqpWGTSB lvhopsmntikraqbeIzMQNRTOVKDdGLPZSCcf"
[0001] DEBUG irc:          ":ircserver 005 relay UHNAMES NAMESX SAFELIST HCN MAXCHANNELS=10 CHANLIMIT=#:10 MAXLIST=b:60,e:60,I:60 MAXNICKLEN=30 NICKLEN=30 CHANNELLEN=32 TOPICLEN=307 KICKLEN=307 AWAYLEN=307 :are supported by this server"
[0001] DEBUG irc:          ":ircserver 005 relay MAXTARGETS=20 WALLCHOPS WATCH=128 WATCHOPTS=A SILENCE=15 MODES=12 CHANTYPES=# PREFIX=(qaohv)~&@%+ CHANMODES=beI,kLf,l,psmntirzMQNRTOVKDdGPZSCc NETWORK=wonderland CASEMAPPING=ascii EXTBAN=~,SOcaRrnqj ELIST=MNUCT :are supported by this server"
[0001] DEBUG irc:          ":ircserver 005 relay STATUSMSG=~&@%+ EXCEPTS INVEX CMDS=USERIP,STARTTLS,KNOCK,DCCALLOW,MAP :are supported by this server"
[0001] DEBUG irc:          ":ircserver 396 relay wonderland-someaddress.xyz :is now your displayed host"
[0001] DEBUG irc:          ":ircserver NOTICE relay :*** You are connected to ircserver with TLSv1.2-ECDHE-RSA-AES256-GCM-SHA384-256bits"
[0001] DEBUG irc:          ":ircserver 251 relay :There are 1 users and 4 invisible on 1 servers"
[0001] DEBUG irc:          ":ircserver 254 relay 1 :channels formed"
[0001] DEBUG irc:          ":ircserver 255 relay :I have 5 clients and 0 servers"
[0001] DEBUG irc:          ":ircserver 265 relay 5 10 :Current local users 5, max 10"
[0001] DEBUG irc:          ":ircserver 266 relay 5 7 :Current global users 5, max 7"
[0001] DEBUG irc:          ":ircserver 422 relay :MOTD File is missing"
[0003] DEBUG irc:          "CLIENT_CONNECTED :ircserver:6697"
[0007] DEBUG irc:          ":relay MODE relay :+iwxz"
[0007]  INFO irc:          Connection succeeded
[0007]  INFO bridge:       irc.ircserver: joining #ircchannel (ID: #ircchannelirc.ircserver)
[0007] DEBUG irc:          ":relay!relay@wonderland-someaddress.xyz JOIN :#ircchannel"
[0007] DEBUG irc:          handleJoinPart: empty Params? girc.Event{Source:(*girc.Source)(0xc000672300), Tags:girc.Tags(nil), Timestamp:time.Time{wall:0xbf1071d6520be4db, ext:6489825134, loc:(*time.Location)(0x1a10ac0)}, Command:"JOIN", Params:[]string(nil), Trailing:"#ircchannel", EmptyTrailing:false, Sensitive:false, Echo:false}
[0007]  INFO main:         Gateway(s) started succesfully. Now relaying messages
[0007] DEBUG irc:          ":ircserver 353 relay = #ircchannel :relay!relay@wonderland-someaddress.xyz User1!4f6f6f21@wonderland-6B2EE0DF011.mibbit.com User2!omni@someaddress3 User3!Miranda@someaddress2 User4!User4@someaddress4 "
[0007] DEBUG irc:          ":ircserver 366 relay #ircchannel :End of /NAMES list."
[0007] DEBUG irc:          ":ircserver 352 relay #ircchannel relay wonderland-someaddress.xyz ircserver relay H :0 relay"
[0007] DEBUG irc:          ":ircserver 352 relay #ircchannel 4f6f6f21 wonderland-6B2EE0DF011.mibbit.com ircserver User1 H :0 someaddress5"
[0007] DEBUG irc:          ":ircserver 352 relay #ircchannel omni someaddress3 ircserver User2 H :0 realname"
[0007] DEBUG irc:          ":ircserver 352 relay #ircchannel Miranda someaddress2 ircserver User3 H :0 User3"
[0007] DEBUG irc:          ":ircserver 352 relay #ircchannel User4 someaddress4 ircserver User4 H :0 User4"
[0007] DEBUG irc:          ":ircserver 315 relay #ircchannel :End of /WHO list."
[0007] DEBUG irc:          ":ircserver 324 relay #ircchannel + "
[0007] DEBUG irc:          ":ircserver 329 relay #ircchannel 1549722268"
[0038] DEBUG irc:          ":User3!Miranda@someaddress2 PRIVMSG #ircchannel :User1, cp1251"
[0038] DEBUG irc:          == Receiving PRIVMSG: User3 User1, cp1251 girc.Event{Source:(*girc.Source)(0xc000930ba0), Tags:girc.Tags(nil), Timestamp:time.Time{wall:0xbf1071de4ae30892, ext:38369706780, loc:(*time.Location)(0x1a10ac0)}, Command:"PRIVMSG", Params:[]string{"#ircchannel"}, Trailing:"User1, cp1251", EmptyTrailing:false, Sensitive:false, Echo:false}
[0038] DEBUG irc:          <= Sending message from #ircchannel on irc.ircserver to gateway
[0038] DEBUG gateway:      => Sending config.Message{Text:"User1, cp1251", Channel:"#ircchannel", Username:"User3", UserID:"Miranda@someaddress2", Avatar:"", Account:"irc.ircserver", Event:"", Protocol:"", Gateway:"irc-to-matrix", ParentID:"", Timestamp:time.Time{wall:0xbf1071de4af34814, ext:38370771561, loc:(*time.Location)(0x1a10ac0)}, ID:"", Extra:map[string][]interface {}(nil)} from irc.ircserver (#ircchannel) to matrix.for_irc (#ircchannel@ircserver:matrixserver)
[0038] DEBUG matrix:       => Receiving config.Message{Text:"User1, cp1251", Channel:"#ircchannel@ircserver:matrixserver", Username:"<User3> ", UserID:"Miranda@someaddress2", Avatar:"", Account:"irc.ircserver", Event:"", Protocol:"", Gateway:"irc-to-matrix", ParentID:"", Timestamp:time.Time{wall:0xbf1071de4af34814, ext:38370771561, loc:(*time.Location)(0x1a10ac0)}, ID:"", Extra:map[string][]interface {}(nil)}
[0038] DEBUG matrix:       Channel #ircchannel@ircserver:matrixserver maps to channel id !dVpkhgsWdfgdgdtGOERLjzWL:matrixserver
[0038] DEBUG gateway:      mID matrix.for_irc: $1549881337179wJSSj:matrixserver
[0038] DEBUG matrix:       == Receiving event: &gomatrix.Event{StateKey:(*string)(nil), Sender:"@.:matrixserver", Type:"m.room.message", Timestamp:1549881337198, ID:"$1549881337179wJSSj:matrixserver", RoomID:"!dVpkhgsWdfgdgdtGOERLjzWL:matrixserver", Content:map[string]interface {}{"msgtype":"m.text", "body":"<User3> User1, cp1251", "format":"org.matrix.custom.html", "formatted_body":"&lt;User3&gt; <p>User1, cp1251</p>\n"}, Redacts:""}
[0061] DEBUG irc:          ":ircserver PONG ircserver :1549881360000647907"
[0121] DEBUG irc:          ":ircserver PONG ircserver :1549881420002715687"
[0181] DEBUG irc:          ":ircserver PONG ircserver :1549881480000644124"
[0190] DEBUG irc:          ":User3!Miranda@someaddress2 PART #ircchannel :I'm a happy Miranda NG user! Get it here: https://miranda-ng.org/"
[0190] DEBUG irc:          <= Sending JOIN_LEAVE event from irc.ircserver to gateway
[0190] DEBUG irc:          <= Message is config.Message{Text:"User3 parts", Channel:"#ircchannel", Username:"system", UserID:"", Avatar:"", Account:"irc.ircserver", Event:"join_leave", Protocol:"", Gateway:"", ParentID:"", Timestamp:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, ID:"", Extra:map[string][]interface {}(nil)}
[0190] DEBUG gateway:      => Sending config.Message{Text:"User3 parts", Channel:"#ircchannel", Username:"system", UserID:"", Avatar:"", Account:"irc.ircserver", Event:"join_leave", Protocol:"", Gateway:"irc-to-matrix", ParentID:"", Timestamp:time.Time{wall:0xbf10720446fe4c1d, ext:190304384629, loc:(*time.Location)(0x1a10ac0)}, ID:"", Extra:map[string][]interface {}(nil)} from irc.ircserver (#ircchannel) to matrix.for_irc (#ircchannel@ircserver:matrixserver)
[0190] DEBUG matrix:       => Receiving config.Message{Text:"User3 parts", Channel:"#ircchannel@ircserver:matrixserver", Username:"<system> ", UserID:"", Avatar:"", Account:"irc.ircserver", Event:"join_leave", Protocol:"", Gateway:"irc-to-matrix", ParentID:"", Timestamp:time.Time{wall:0xbf10720446fe4c1d, ext:190304384629, loc:(*time.Location)(0x1a10ac0)}, ID:"", Extra:map[string][]interface {}(nil)}
[0190] DEBUG matrix:       Channel #ircchannel@ircserver:matrixserver maps to channel id !dVpkhgsWdfgdgdtGOERLjzWL:matrixserver
[0190] DEBUG gateway:      mID matrix.for_irc: $1549881489180nFBLF:matrixserver
[0190] DEBUG matrix:       == Receiving event: &gomatrix.Event{StateKey:(*string)(nil), Sender:"@.:matrixserver", Type:"m.room.message", Timestamp:1549881489133, ID:"$1549881489180nFBLF:matrixserver", RoomID:"!dVpkhgsWdfgdgdtGOERLjzWL:matrixserver", Content:map[string]interface {}{"msgtype":"m.text", "body":"<system> User3 parts", "format":"org.matrix.custom.html", "formatted_body":"&lt;system&gt; <p>User3 parts</p>\n"}, Redacts:""}
[0198] DEBUG irc:          ":User3!Miranda@someaddress2 JOIN :#ircchannel"
[0198] DEBUG irc:          handleJoinPart: empty Params? girc.Event{Source:(*girc.Source)(0xc000b43290), Tags:girc.Tags(nil), Timestamp:time.Time{wall:0xbf10720655118157, ext:198540524516, loc:(*time.Location)(0x1a10ac0)}, Command:"JOIN", Params:[]string(nil), Trailing:"#ircchannel", EmptyTrailing:false, Sensitive:false, Echo:false}
[0198] DEBUG irc:          ":ircserver 352 relay #ircchannel Miranda someaddress2 ircserver User3 H :0 User3"
[0198] DEBUG irc:          ":ircserver 315 relay User3 :End of /WHO list."
[0241] DEBUG irc:          ":ircserver PONG ircserver :1549881540000714684"

<...>

[0611] DEBUG irc:          ":User1!4f6f6f21@wonderland-6B2EE0DF011.mibbit.com PART #ircchannel"
[0611] DEBUG irc:          <= Sending JOIN_LEAVE event from irc.ircserver to gateway
[0611] DEBUG irc:          <= Message is config.Message{Text:"User1 parts", Channel:"#ircchannel", Username:"system", UserID:"", Avatar:"", Account:"irc.ircserver", Event:"join_leave", Protocol:"", Gateway:"", ParentID:"", Timestamp:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, ID:"", Extra:map[string][]interface {}(nil)}
[0611] DEBUG gateway:      => Sending config.Message{Text:"User1 parts", Channel:"#ircchannel", Username:"system", UserID:"", Avatar:"", Account:"irc.ircserver", Event:"join_leave", Protocol:"", Gateway:"irc-to-matrix", ParentID:"", Timestamp:time.Time{wall:0xbf10726d89cfba5d, ext:611351664351, loc:(*time.Location)(0x1a10ac0)}, ID:"", Extra:map[string][]interface {}(nil)} from irc.ircserver (#ircchannel) to matrix.for_irc (#ircchannel@ircserver:matrixserver)
[0611] DEBUG matrix:       => Receiving config.Message{Text:"User1 parts", Channel:"#ircchannel@ircserver:matrixserver", Username:"<system> ", UserID:"", Avatar:"", Account:"irc.ircserver", Event:"join_leave", Protocol:"", Gateway:"irc-to-matrix", ParentID:"", Timestamp:time.Time{wall:0xbf10726d89cfba5d, ext:611351664351, loc:(*time.Location)(0x1a10ac0)}, ID:"", Extra:map[string][]interface {}(nil)}
[0611] DEBUG matrix:       Channel #ircchannel@ircserver:matrixserver maps to channel id !dVpkhgsWdfgdgdtGOERLjzWL:matrixserver
[0611] DEBUG gateway:      mID matrix.for_irc: $1549881910181RTMbo:matrixserver
[0611] DEBUG matrix:       == Receiving event: &gomatrix.Event{StateKey:(*string)(nil), Sender:"@.:matrixserver", Type:"m.room.message", Timestamp:1549881910191, ID:"$1549881910181RTMbo:matrixserver", RoomID:"!dVpkhgsWdfgdgdtGOERLjzWL:matrixserver", Content:map[string]interface {}{"msgtype":"m.text", "body":"<system> User1 parts", "format":"org.matrix.custom.html", "formatted_body":"&lt;system&gt; <p>User1 parts</p>\n"}, Redacts:""}
[0626] DEBUG irc:          ":User1!4f6f6f21@wonderland-6B2EE0DF011.mibbit.com JOIN :#ircchannel"
[0626] DEBUG irc:          handleJoinPart: empty Params? girc.Event{Source:(*girc.Source)(0xc000b769c0), Tags:girc.Tags(nil), Timestamp:time.Time{wall:0xbf1072714b295f28, ext:626374316466, loc:(*time.Location)(0x1a10ac0)}, Command:"JOIN", Params:[]string(nil), Trailing:"#ircchannel", EmptyTrailing:false, Sensitive:false, Echo:false}
[0626] DEBUG irc:          ":ircserver 352 relay #ircchannel 4f6f6f21 wonderland-6B2EE0DF011.mibbit.com ircserver User1 H :0 someaddress5"
[0626] DEBUG irc:          ":ircserver 315 relay User1 :End of /WHO list."
```

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Matterbridge version: 1.13.2-dev, 2cfd880cdb0df29771bf8f31df8d990ab897889d

**Additional context**
matterbridge.toml:
```
[irc.ircserver]
Server="ircserver:6697"
Password=""
UseTLS=true
SkipTLSVerify=true
Charset="windows-1251"
Nick="relay"
MessageSplit=true
MessageLength=1000
RejoinDelay=1
RunCommands=["JOIN #ircchannel"]
RemoteNickFormat="<{NICK}> "
ShowJoinPart=true
ShowTopicChange=true
debuglevel=1
[matrix.for_irc]
Server="https://matrix.matrixserver"
RemoteNickFormat="<{NICK}> "
ShowJoinPart=true
ShowTopicChange=true
NoHomeServerSuffix=true
[[gateway]]
name="irc-to-matrix"
enable=true
[[gateway.inout]]
account="matrix.for_irc"
channel="#ircchannel@ircserver:matrixserver"
[[gateway.inout]]
account="irc.ircserver"
channel="#ircchannel"
```

**Comment by 42wim** [comment]
Well, it does show joins if you use for example freenode.
It seems like unrealircd you're using isn't following RFC, it adds a `:` before the channel.

`[0626] DEBUG irc:          ":User1!4f6f6f21@wonderland-6B2EE0DF011.mibbit.com JOIN :#ircchannel"`
is very strange, should be
`[0626] DEBUG irc:          ":User1!4f6f6f21@wonderland-6B2EE0DF011.mibbit.com JOIN #ircchannel"`

**Comment by 42wim** [comment]
I tried this on irc.unrealircd.org but can't reproduce it.

**Comment by qaisjp** [comment]
Is it possible that it was fixed by https://github.com/lrstanley/girc/pull/36?

**Comment by Ossssip** [comment]
Unfortunately, that’s not a public server. And yes, unrealircd [adds a semicolon before the channel name](https://github.com/unrealircd/unrealircd/blob/1e1f750b443c802b4ef10a774c6fa3d61bfdbc1e/src/modules/m_join.c#L189). 
I have rebuild matterbridge anew (that should include https://github.com/lrstanley/girc/pull/36, right?), but the issue still persists.
I am not familiar with the irc RFC, but just from reading https://github.com/lrstanley/girc/issues/35, the trailing parameter might start with a semicolon. Am I looking at the wrong place?

**Comment by 42wim** [comment]
No matterbridge hasn't been updated yet for https://github.com/lrstanley/girc/pull/36 (haven't got the time yet for this)

Could you test/confirm if you have or not have the issue on irc.unrealircd.org?

**Comment by Ossssip** [comment]
I have tested it on irc.unrealircd.org, and it works fine. The server does not prepend `:` before the channel name, and joins are handled correctly.

**Comment by 42wim** [comment]
@Ossssip ok, thanks for testing.

I've just merged the latest girc upgrade in master. 
Can you try rebuild from master or download the dev binaries from https://bintray.com/42wim/nightly/Matterbridge/v1.13.1-14-g3123695#files

**Comment by Ossssip** [comment]
With the new version it works fine. Thanks!

**Comment by chotaire** [comment]
I am having similar issues, but for me it's the other way around. I can see joins, but no parts and quits when relaying to Rocketchat or to another IRC channel.

Tested irc servers: ngircd and InspIRCd (both latest stable version). 
matterbridge version: matterbridge-v1.14.2-10-g380c386-linux-amd64
